CREATE TABLE PESSOA (
    ID NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1), -- criando um ID sintético
    CPF CHAR(11) NOT NULL,
    NOME VARCHAR2(80),
    RG VARCHAR2(9) NOT NULL, -- tamanho do RG varia de estado
    UF CHAR(2) NOT NULL,
    DATA_NASCIMENTO DATE,
    RUA VARCHAR2(100),
    NUMERO NUMBER,
    COMPLEMENTO VARCHAR2(20),
    BAIRRO VARCHAR2(25),
    CIDADE VARCHAR2(30),

    CONSTRAINT PK_PESSOA PRIMARY KEY (ID),
    CONSTRAINT SK_PESSOA UNIQUE (CPF),
    CONSTRAINT TK_PESSOA_RG UNIQUE (RG, UF), -- RG em cada estado não se repete
    CONSTRAINT CK_PESSOA_CPF CHECK (LENGTH(CPF) = 11), -- CPF sempre tem 11 caracteres
    CONSTRAINT CK_PESSOA_UF CHECK (UF IN ('AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO'))
);

create table PACIENTE(
    ID_PESSOA NUMBER,
    TIPO_SANGUINEO VARCHAR2(2),
    FATOR_RH CHAR(1),
    ALTURA NUMBER(5,2),
    PESO NUMBER(5,2),

    CONSTRAINT PK_PACIENTE PRIMARY KEY (ID_PESSOA),
    CONSTRAINT CK_TIPO_SANGUINEO CHECK (TIPO_SANGUINEO IN ('A', 'B', 'AB', 'O')),
    CONSTRAINT CK_FATOR_RH CHECK (FATOR_RH IN ('+', '-')),
    CONSTRAINT FK_PACIENTE FOREIGN KEY (ID_PESSOA) REFERENCES PESSOA(ID) ON DELETE CASCADE
);

CREATE TABLE CONDUTOR(
    ID_PESSOA NUMBER,
    DOCUMENTO_HABILITACAO VARCHAR2(11) NOT NULL, -- varia para cada documento de habilitação

    CONSTRAINT PK_CONDUTOR PRIMARY KEY (ID_PESSOA),
    CONSTRAINT SK_CONDUTOR UNIQUE (DOCUMENTO_HABILITACAO),
    CONSTRAINT FK_CONDUTOR FOREIGN KEY (ID_PESSOA) REFERENCES PESSOA(ID) ON DELETE CASCADE

);

CREATE TABLE EQUIPE_MEDICA(
    ID_PESSOA NUMBER,
    DOCUMENTO_PROFISSIONAL_SAUDE VARCHAR2(15) NOT NULL,
    CARGO VARCHAR2(15),

    CONSTRAINT PK_MEDICO PRIMARY KEY (ID_PESSOA),
    CONSTRAINT SK_MEDICO UNIQUE (DOCUMENTO_PROFISSIONAL_SAUDE),
    CONSTRAINT FK_MEDICO FOREIGN KEY (ID_PESSOA) REFERENCES PESSOA(ID) ON DELETE CASCADE,
    CONSTRAINT CK_EQUIPE CHECK (CARGO IN ('MEDICO', 'ENFERMEIRO', 'TECNICO_ENFERMAGEM'))
);

CREATE TABLE VINCULOS(
    ID_PESSOA NUMBER,
    VINCULO VARCHAR2(20) NOT NULL,

    CONSTRAINT PK_VINCULOS PRIMARY KEY (ID_PESSOA, VINCULO),
    CONSTRAINT CK_TIPO_VINCULO CHECK (VINCULO IN ('PACIENTE', 'CONDUTOR', 'EQUIPE_MEDICA')),
    CONSTRAINT FK_VINCULOS FOREIGN KEY (ID_PESSOA) REFERENCES PESSOA(ID) ON DELETE CASCADE
);

CREATE TABLE COMORBIDADES(
    ID_PACIENTE NUMBER, -- que é o mesmo ID de PESSOA
    COMORBIDADE VARCHAR2(20) NOT NULL,

    CONSTRAINT PK_COMORBIDADES PRIMARY KEY (ID_PACIENTE, COMORBIDADE),
    CONSTRAINT FK_COMORBIDADES FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(ID_PESSOA) ON DELETE CASCADE
);

CREATE TABLE PAPEIS(
    ID_PACIENTE NUMBER, -- que é o mesmo ID de PESSOA
    PAPEL VARCHAR2(20) NOT NULL,

    CONSTRAINT PK_PAPEIS PRIMARY KEY (ID_PACIENTE, PAPEL),
    CONSTRAINT FK_PAPEIS FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(ID_PESSOA) ON DELETE CASCADE
);

CREATE TABLE CONSULTA(
    ID_PACIENTE NUMBER, -- que é o mesmo ID de PESSOA
    ID_MEDICO NUMBER, -- que é o mesmo ID de PESSOA
    DATA_HORA DATE NOT NULL,

    CONSTRAINT PK_CONSULTA PRIMARY KEY (ID_PACIENTE, ID_MEDICO, DATA_HORA),
    CONSTRAINT FK_CONSULTA_PACIENTE FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(ID_PESSOA) ON DELETE CASCADE,
    CONSTRAINT FK_CONSULTA_MEDICO FOREIGN KEY (ID_MEDICO) REFERENCES EQUIPE_MEDICA(ID_PESSOA) ON DELETE SET NULL -- permite que o médico seja removido sem excluir a consulta
);

CREATE TABLE RECEPTOR(
    ID_PACIENTE NUMBER, -- que é o mesmo ID de PESSOA

    CONSTRAINT PK_RECEPTOR PRIMARY KEY (ID_PACIENTE),
    CONSTRAINT FK_RECEPTOR FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(ID_PESSOA) ON DELETE CASCADE
);

CREATE TABLE DOADOR(
    ID_PACIENTE NUMBER, -- que é o mesmo ID de PESSOA
    ESTADO_SAUDE VARCHAR2(20),

    CONSTRAINT PK_DOADOR PRIMARY KEY (ID_PACIENTE),
    CONSTRAINT FK_DOADOR FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(ID_PESSOA) ON DELETE CASCADE
);

CREATE TABLE MORTO(
    ID_DOADOR NUMBER, -- que é o mesmo ID de PESSOA
    DATA_HORA DATE NOT NULL,
    CAUSA VARCHAR2(50),

    CONSTRAINT PK_MORTO PRIMARY KEY (ID_DOADOR),
    CONSTRAINT FK_MORTO FOREIGN KEY (ID_DOADOR) REFERENCES DOADOR(ID_PACIENTE) ON DELETE CASCADE
);

CREATE TABLE TIPO_ORGAO(
    CODIGO CHAR(3), -- string de 3 caracteres, PUL, COR, RIM etc.

    CONSTRAINT PK_TIPO_ORGAO PRIMARY KEY (CODIGO)   
);

CREATE TABLE LISTA_ESPERA(
    ID_RECEPTOR NUMBER,
    TIPO_ORGAO CHAR(3),
    DATA_HORA_ENTRADA DATE,
    DATA_HORA_SAIDA DATE,
    POSICAO NUMBER,

    CONSTRAINT PK_LISTA_ESPERA PRIMARY KEY (ID_RECEPTOR, TIPO_ORGAO, DATA_HORA_ENTRADA),
    CONSTRAINT FK_LISTA_RECEPTOR FOREIGN KEY (ID_RECEPTOR) REFERENCES RECEPTOR(ID_PACIENTE) ON DELETE CASCADE,
    CONSTRAINT FK_LISTA_TIPO FOREIGN KEY (TIPO_ORGAO) REFERENCES TIPO_ORGAO(CODIGO) ON DELETE CASCADE
);

CREATE TABLE HOSPITAL(
    CNPJ CHAR(14), 
    NOME VARCHAR2(30),
    RUA VARCHAR2(100),
    NUMERO NUMBER,
    COMPLEMENTO VARCHAR2(20),
    BAIRRO VARCHAR2(25),
    CIDADE VARCHAR2(30),
    TELEFONE CHAR(11),

    CONSTRAINT PK_HOSPITAL PRIMARY KEY (CNPJ)
);

CREATE TABLE VIAGEM(
    ID NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    DATA_HORA_INICIO DATE NOT NULL,
    HOSPITAL_ORIGEM CHAR(14) NOT NULL,
    HOSPITAL_DESTINO CHAR(14) NOT NULL,

    CONSTRAINT PK_VIAGEM PRIMARY KEY (ID),
    CONSTRAINT SK_VIAGEM UNIQUE (DATA_HORA_INICIO, HOSPITAL_ORIGEM),
    CONSTRAINT FK_VIAGEM_HOSPITAL_ORIGEM FOREIGN KEY (HOSPITAL_ORIGEM) REFERENCES HOSPITAL(CNPJ) ON DELETE SET NULL,
    CONSTRAINT FK_VIAGEM_HOSPITAL_DESTINO FOREIGN KEY (HOSPITAL_DESTINO) REFERENCES HOSPITAL(CNPJ) ON DELETE SET NULL
);

CREATE TABLE ORGAO_ESPECIFICO(
    ID NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    ID_DOADOR NUMBER NOT NULL,
    TIPO_ORGAO CHAR(3) NOT NULL,
    DATA_HORA DATE NOT NULL,
    LATERALIDADE CHAR(1),
    DATA_ISQUEMIA TIMESTAMP, -- data armazenada no lugar do tempo para facilitar a inserção: quando precisar do tempo, o banco calcula
    -- foi utilizado TIMESTAMP para o cálculo de horas, não apenas de dias
    STATUS VARCHAR2(15),
    ID_VIAGEM NUMBER,

    CONSTRAINT PK_ORGAO_ESPECIFICO PRIMARY KEY (ID),
    CONSTRAINT SK_ORGAO_ESPECIFICO UNIQUE (ID_DOADOR, TIPO_ORGAO, DATA_HORA),
    CONSTRAINT CK_TIPO_ORGAO CHECK (LATERALIDADE IN ('D', 'E')),
    CONSTRAINT FK_ORGAO_DOADOR FOREIGN KEY (ID_DOADOR) REFERENCES DOADOR(ID_PACIENTE) ON DELETE CASCADE,
    CONSTRAINT FK_ORGAO_VIAGEM FOREIGN KEY (ID_VIAGEM) REFERENCES VIAGEM(ID) ON DELETE SET NULL,
    CONSTRAINT FK_ORGAO_TIPO FOREIGN KEY (TIPO_ORGAO) REFERENCES TIPO_ORGAO(CODIGO) ON DELETE CASCADE
);

CREATE TABLE VEICULO(
    PLACA CHAR(7),
    MODELO VARCHAR2(30),
    MEIO_TRANSPORTE VARCHAR2(20),

    CONSTRAINT PK_VEICULO PRIMARY KEY (PLACA)
);

CREATE TABLE TRECHO(
    ID_VIAGEM NUMBER,
    DATA_HORA_PARTIDA DATE,
    DATA_HORA_CHEGADA DATE,
    LOCAL_PARTIDA VARCHAR2(100),
    LOCAL_DESTINO VARCHAR2(100),
    VEICULO CHAR(7) NOT NULL,

    CONSTRAINT PK_TRECHO PRIMARY KEY (ID_VIAGEM, DATA_HORA_PARTIDA),
    CONSTRAINT FK_TRECHO_VIAGEM FOREIGN KEY (ID_VIAGEM) REFERENCES VIAGEM(ID) ON DELETE CASCADE,
    CONSTRAINT FK_TRECHO_VEICULO FOREIGN KEY (VEICULO) REFERENCES VEICULO(PLACA) ON DELETE SET NULL
);

CREATE TABLE TRANSPLANTE(
    ID_ORGAO NUMBER,
    ID_RECEPTOR NUMBER NOT NULL,
    DATA_HORA_IMPLANTE DATE,
    STATUS VARCHAR2(15),
    HOSPITAL CHAR(14) NOT NULL,

    CONSTRAINT PK_TRANSPLANTE PRIMARY KEY (ID_ORGAO), -- foi retirada a data/hora do implante para manter a cardinalidade 1:1
    CONSTRAINT FK_TRANSPLANTE_ORGAO FOREIGN KEY (ID_ORGAO) REFERENCES ORGAO_ESPECIFICO(ID) ON DELETE CASCADE,
    CONSTRAINT FK_TRANSPLANTE_RECEPTOR FOREIGN KEY (ID_RECEPTOR) REFERENCES RECEPTOR(ID_PACIENTE) ON DELETE CASCADE,
    CONSTRAINT FK_TRANSPLANTE_HOSPITAL FOREIGN KEY (HOSPITAL) REFERENCES HOSPITAL(CNPJ) ON DELETE SET NULL
);

CREATE TABLE RESPONSAVEL(
    ID_PROFISSIONAL_SAUDE NUMBER,
    ORGAO_TRANSPLANTE NUMBER,
    
    CONSTRAINT PK_RESPONSAVEL PRIMARY KEY (ID_PROFISSIONAL_SAUDE, ORGAO_TRANSPLANTE),
    CONSTRAINT FK_RESPONSAVEL_MEDICO FOREIGN KEY (ID_PROFISSIONAL_SAUDE) REFERENCES EQUIPE_MEDICA(ID_PESSOA) ON DELETE SET NULL,
    CONSTRAINT FK_RESPONSAVEL_ORGAO FOREIGN KEY (ORGAO_TRANSPLANTE) REFERENCES TRANSPLANTE(ID_ORGAO) ON DELETE SET NULL
);

CREATE TABLE COMPLICACOES(
    ID_ORGAO NUMBER,
    COMPLICACAO VARCHAR2(50) NOT NULL,

    CONSTRAINT PK_COMPLICACOES PRIMARY KEY (ID_ORGAO, COMPLICACAO),
    CONSTRAINT FK_COMPLICACOES_ORGAO FOREIGN KEY (ID_ORGAO) REFERENCES TRANSPLANTE(ID_ORGAO) ON DELETE CASCADE
);

CREATE TABLE REALIZA(
    ID_CONDUTOR NUMBER,
    ID_TRECHO_VIAGEM NUMBER,
    DATA_HORA_PARTIDA_TRECHO DATE,

    CONSTRAINT PK_REALIZA PRIMARY KEY (ID_CONDUTOR, ID_TRECHO_VIAGEM, DATA_HORA_PARTIDA_TRECHO),
    CONSTRAINT FK_REALIZA_CONDUTOR FOREIGN KEY (ID_CONDUTOR) REFERENCES CONDUTOR(ID_PESSOA) ON DELETE CASCADE,
    CONSTRAINT FK_REALIZA_TRECHO_VIAGEM FOREIGN KEY (ID_TRECHO_VIAGEM, DATA_HORA_PARTIDA_TRECHO) REFERENCES TRECHO(ID_VIAGEM, DATA_HORA_PARTIDA) ON DELETE CASCADE
);

/* Triggers para garantias de especialização */


/* Automação de VINCULOS (PESSOA -> Especializações) */

-- 1. Trigger para EQUIPE_MEDICA
CREATE OR REPLACE TRIGGER TRG_AUTO_VINCULO_EQUIPE
AFTER INSERT ON EQUIPE_MEDICA
FOR EACH ROW
BEGIN
    INSERT INTO VINCULOS (ID_PESSOA, VINCULO)
    VALUES (:NEW.ID_PESSOA, 'EQUIPE_MEDICA');
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN NULL; -- Verifica se ja existe, se sim, ignora
END;
/

-- 2. Trigger para CONDUTOR
CREATE OR REPLACE TRIGGER TRG_AUTO_VINCULO_CONDUTOR
AFTER INSERT ON CONDUTOR
FOR EACH ROW
BEGIN
    INSERT INTO VINCULOS (ID_PESSOA, VINCULO)
    VALUES (:NEW.ID_PESSOA, 'CONDUTOR');
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

-- 3. Trigger para PACIENTE
CREATE OR REPLACE TRIGGER TRG_AUTO_VINCULO_PACIENTE
AFTER INSERT ON PACIENTE
FOR EACH ROW
BEGIN
    INSERT INTO VINCULOS (ID_PESSOA, VINCULO)
    VALUES (:NEW.ID_PESSOA, 'PACIENTE');
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

/* Automação de PAPEIS (PACIENTE -> RECEPTOR/DOADOR) */
-- 4. Trigger para RECEPTOR
CREATE OR REPLACE TRIGGER TRG_AUTO_PAPEL_RECEPTOR
AFTER INSERT ON RECEPTOR
FOR EACH ROW
BEGIN
    INSERT INTO PAPEIS (ID_PACIENTE, PAPEL)
    VALUES (:NEW.ID_PACIENTE, 'RECEPTOR');
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

-- 5. Trigger para DOADOR
CREATE OR REPLACE TRIGGER TRG_AUTO_PAPEL_DOADOR
AFTER INSERT ON DOADOR
FOR EACH ROW
BEGIN
    INSERT INTO PAPEIS (ID_PACIENTE, PAPEL)
    VALUES (:NEW.ID_PACIENTE, 'DOADOR');
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/